# Generated by Django 2.2.7 on 2020-02-01 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('nome', models.CharField(max_length=120)),
                ('registro', models.CharField(max_length=11, unique=True)),
                ('cpf', models.CharField(max_length=11)),
                ('funcao', models.CharField(blank=True, max_length=35, null=True)),
                ('cargo', models.CharField(max_length=50)),
                ('lotacao', models.CharField(max_length=35)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Novo'), ('2', 'Visualizado')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pauta', models.CharField(max_length=120)),
                ('local', models.CharField(max_length=120)),
                ('semestre', models.CharField(max_length=6)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('deliberacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Agendada'), ('2', 'Confirmada'), ('3', 'Consolidada'), ('4', 'Cancelada')], default='1', max_length=1)),
                ('cor', models.CharField(choices=[('1', '#FFF176'), ('2', '#4CAF50'), ('3', '#78909C'), ('4', '#FF5722')], default='1', max_length=1)),
                ('data_reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Data')),
                ('participantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('tipo_reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tipo')),
            ],
        ),
    ]
