# Generated by Django 2.2.7 on 2020-01-25 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reuniao',
            name='participantes',
        ),
        migrations.AddField(
            model_name='reuniao',
            name='participantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
