# Generated by Django 2.2.7 on 2019-11-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Novo'), ('2', 'Visualizado')], default='1', max_length=1)),
            ],
        ),
    ]
