# Generated by Django 2.2.7 on 2020-03-06 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200306_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='chefia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
