# Generated by Django 2.2.7 on 2020-03-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200306_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={'verbose_name_plural': 'Alertas'},
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Datas'},
        ),
        migrations.AlterModelOptions(
            name='reuniao',
            options={'verbose_name_plural': 'Reuniões'},
        ),
    ]
