# Generated by Django 2.2.7 on 2020-03-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alerta_acao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='acao',
        ),
        migrations.AddField(
            model_name='alerta',
            name='identificador',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='url',
            field=models.CharField(default='vizualizar', max_length=120),
        ),
    ]
