# Generated by Django 2.2.7 on 2020-03-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200307_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='identificador',
            field=models.CharField(default='0', max_length=120),
        ),
    ]
