# Generated by Django 2.2.7 on 2020-03-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200307_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='alters_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
